name: deploy

permissions:
  contents: write # required to make a release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-binaries:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install Rust
      run: rustup toolchain install --profile minimal --override stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload binary
      uses: actions/upload-artifact@v7
      with:
        path: target/release/av-metrics-tool.exe

  deploy:
    needs: [create-binaries]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Download binary
      uses: actions/download-artifact@v8

    - name: Handle release data and files
      id: data
      run: |
        VERSION=$(grep -m 1 '^## Version' CHANGELOG.md | sed 's/## Version //')
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        awk 'BEGIN{p=0} /^## /{if(p) exit; p=1; next} p{print}' CHANGELOG.md > CHANGELOG.txt
        strip av-metrics-tool.exe

    - name: Create a release
      uses: softprops/action-gh-release@v3
      with:
        name: Version ${{ steps.data.outputs.version }}
        body_path: CHANGELOG.txt
        files: av-metrics-tool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
